version: '3.4'


services:
     
    mssqlserver:
        image: microsoft/mssql-server-linux:latest
        container_name: mssqlcontainer
        ports:
          - "1445:1433"
        environment:
          - ACCEPT_EULA=Y 
          - MSSQL_PID=Developer
          - SA_PASSWORD=8jkGh47hnDw89Haq8LN2

    basketdata:
        image: redis
        ports:
            - "6733:6379"
 
    catalog:
        build:
            context: .\src\services\ProductCatalogApi
            dockerfile: Dockerfile
        environment:
            - DatabaseServer=mssqlserver
            - DatabaseName=CatalogDb
            - DatabaseUser=sa
            - DatabaseNamePassword=8jkGh47hnDw89Haq8LN2
        image: shoes/catalog
        container_name: catalogapi
        ports:
            - "5100:80"
        depends_on:
            - mssqlserver

    client:
        build:
            context: .\src\web\client
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - CatalogUrl=http://catalog
            - IdentityUrl=http://10.0.75.1:5000
        container_name: client
        ports:
            - "5200:80"
        depends_on:
            - catalog
            - tokenserver
     
    tokenserver:
        build:
            context: .\src\services\tokenserviceapi
            dockerfile: Dockerfile
        environment:
            - MvcClient=http://localhost:5200
            - BasketApiClient=http://localhost:5500
            - IDENTITY_ISSUER=http://10.0.75.1:5000
            - OrderApiClient=http://localhost:5600
            - DatabaseServer=mssqlserver
            - DatabaseName=TokenServiceDb
            - DatabaseUser=sa
            - DatabaseNamePassword=8jkGh47hnDw89Haq8LN2
        container_name: tokenserviceapi
        ports:
            - "5000:80"
        depends_on: 
            - mssqlserver

    cart:
        image: cartimage
        build:
            context: .\src\Services\CartApi
            dockerfile: Dockerfile
        environment:
            -  ASPNETCORE_ENVIRONMENT=Development
            - ConnectionString=basketdata
            - IdentityUrl=http://10.0.75.1:5000
        container_name: cartapi
        ports:
            - "5500:80"
        depends_on:
            - basketdata
            - tokenserver