version: '3.4'

services:
    mssqlserver:
        image: microsoft/mssql-server-linux:latest
        container_name: mssqlcontainer
        ports:
          - "1445:1433"
        environment:
          - ACCEPT_EULA=Y 
          - MSSQL_PID=Developer
          - SA_PASSWORD=8jkGh47hnDw89Haq8LN2

    tokenserver:
        build:
            context: .\src\services\tokenserviceapi
            dockerfile: Dockerfile
        environment:
            - MvcClient=http://localhost:5200
            - BasketApiClient=http://localhost:5500
            - OrderApiClient=http://localhost:5600
            - IDENTITY_ISSUER=http://10.0.75.1:5000
            - DatabaseServer=mssqlserver
            - DatabaseName=TokenServiceDb
            - DatabaseUser=sa
            - DatabaseNamePassword=8jkGh47hnDw89Haq8LN2
        container_name: tokenserviceapi
        ports:
            - "5000:80"
        depends_on: 
            - mssqlserver

    order.server:
        container_name: ${MYSQL_SERVER_NAME}
        image: mysql
        restart: always
        volumes: 
            - odata:/var/lib/mysql
        ports:
            - "3406:3306"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: !!str yes
        env_file:
            - secrets.env
    

volumes:
    odata: