version: '3'

networks:
    frontend:
    backend:


services:
     
    mssqlserver:
        image: microsoft/mssql-server-linux:latest
        container_name: mssqlcontainer
        ports:
          - "1445:1433"
        environment:
          - ACCEPT_EULA=Y 
          - MSSQL_PID=Developer
          - SA_PASSWORD=8jkGh47hnDw89Haq8LN2
        networks:
            - backend

    catalog:
        build:
            context: .\src\services\ProductCatalogApi
            dockerfile: Dockerfile
        environment:
            - DatabaseServer=mssqlserver
            - DatabaseName=CatalogDb
            - DatabaseUser=sa
            - DatabaseNamePassword=8jkGh47hnDw89Haq8LN2
        image: shoes/catalog
        container_name: catalogapi
        ports:
            - "5000:80"
        networks: 
            - backend
            - frontend
        depends_on:
            - mssqlserver

    client:
        build:
            context: .\src\web\client
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - CatalogUrl=http://catalog
        container_name: client
        ports:
            - "5500:80"
        networks:
            - frontend
        depends_on:
            - catalog